name: "Truma inetbox"
description: "Transform Home Assistant into a Inetbox to control mobile heater and AC of your caravan."
version: "1.0.0"
slug: "inetbox"
init: false
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: "INFO"
  host: "core-mosquitto"
  port: 1883
  username: ""
  password: ""
  keepalive: 60
  serial_device: "/dev/serial0"
  baudrate: 9600
  timeout: 0.5
  use_tls: false
  cert_reqs: CERT_REQUIRED
  ca_certs: ca.pem
  certfile: client.pem
  keyfile: key.pem
  tls_version: PROTOCOL_TLS
  ciphers: None
schema:
  log_level: list(NOTSET|DEBUG|INFO|WARNING|ERROR|CRITICAL)
  host: str
  username: str
  password: password
  port: port
  keepalive: int
  serial_device: str
  baudrate: int
  timeout: float(0.1,)
  use_tls: bool
  cert_reqs: list(CERT_NONE|CERT_OPTIONAL|CERT_REQUIRED)
  ca_certs: str
  certfile: str
  keyfile: str
  tls_version: list(PROTOCOL_TLS|PROTOCOL_TLS_CLIENT|PROTOCOL_TLS_SERVER|PROTOCOL_SSLv3)
  ciphers: str
